### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by walksanatora** [lunofe/PeskyPirates#1]
mabey instead suggest this mod to be Jar in Jar'd
also a more general method of detection is see if you can ping mojang.com auth servers and the game is still in offline mode

**Comment by walksanatora** [comment]
also dont crash directly
but instead do something that will cause a crash later down the line. mabey a null pointer somewhere?

**Comment by walksanatora** [comment]
that or just ... terminate? why does it have to be a crash, why not just close it and leave a trace of what your mod did?

**Comment by lunofe** [comment]
I'll look into terminating instead of throwing a crash, but sadly the more general check you described won't work with TLauncher, as it provides a fake UUID and AccessToken, without tampering with the authentication servers in a way that would be detected by the game.
![image](https://github.com/lunofe/PeskyPirates/assets/42828197/7b664bcf-8b52-40ef-82ef-15ece49947e5)
